-- ALTER TABLE MARAVILLA CHANGE COLUMN APELLIDOS NOMBRE_CREADOR varchar(40) NOT NULL;  

 -- ALTER TABLE MARAVILLA RENAME COLUMN APELLIDOS TO NOMBRE_CREADOR;

 -- RENAME COLUMN MARAVILLA.APELLIDOS TO NOMBRE_CREADOR;

--- RENAME TABLE table-Name TO new-Table-Name


ALTER TABLE MARAVILLA DROP COLUMN NUM_HIJOS;  